# Generated by Django 4.0.4 on 2023-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_loginuser_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetname', models.CharField(max_length=50)),
                ('assetserialNo', models.IntegerField()),
                ('assetmanufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
