# Generated by Django 4.0.4 on 2023-02-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='assetname',
            new_name='assetname',
        ),
    ]
