# Generated by Django 4.0.4 on 2023-02-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_asset_name_entry_assetname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='assetmanufacturer',
            new_name='assetmanufacturer',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='assetserialNo',
            new_name='assetserialNo',
        ),
    ]
