# Generated by Django 4.0.4 on 2023-02-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_asset_manufacturer_entry_assetmanufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='assetserialNo',
            new_name='assetserialNo',
        ),
    ]
