# Generated by Django 4.0.4 on 2023-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_assetserial_no_entry_assetserialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dropdown',
            field=models.CharField(default='value', max_length=20),
        ),
    ]
