# Generated by Django 4.0.4 on 2023-02-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_registration_alter_restaurant_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
